start =
	expression

validchar
	= [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =
	chars:validchar+
	{ return chars.join(""); }

molecule =
	emptyMolecule
	/ fullMolecule

emptyMolecule =
	"(" ")"
	{ return []; }
    
spaceAtom =
	" " theAtom:expression
	{ return theAtom; }

fullMolecule =
	"(" firstAtom:expression restAtom:spaceAtom* ")"
	{ return [firstAtom].concat(restAtom); }

expression =
	atom
	/ molecule